version: '3.8'

services:
  dbnce:
    image: postgres:14
    restart: always
    container_name: 'postgres_nce'
    environment:
        POSTGRES_PASSWORD: ''
        POSTGRES_USER: 'postgres'
        POSTGRES_DB: "blockscout"
        POSTGRES_HOST_AUTH_METHOD: 'trust'
    ports:
      - 7432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
