version: '3.0'
services:
  blockscout:
    image: blockscout/blockscout:latest
    restart: always
    container_name: 'blockscout'
   # links:
   #   - dbnce:database
    command: bash -c "bin/blockscout eval \"Elixir.Explorer.ReleaseTasks.create_and_migrate()\" && bin/blockscout start"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file:
      -  ./envs/common-blockscout.env
    ports:
      - 4000:4000
